###############################################################################
# Book settings
title       : Vorlesung Ingenieurinformatik
author      : ''
logo        : 'cce_logo.png'
description : Dieses Buch ist das Skript zur Vorlesung 'Ingeneursinformatik' an der Bergischen Universität Wuppertal.

###############################################################################
# Exclude settings
exclude_patterns : [.venv/*]

###############################################################################
# Execution settings
execute:
  execute_notebooks : cache
  timeout           : 120

###############################################################################
# TOC settings
only_build_toc_files : true
number_toc_chapters: true

###############################################################################
# HTML-specific settings
html:
  favicon               : 'cce_logo_standalone_icon.png'
  home_page_in_navbar   : False
  baseurl               : 'https://firedynamics.github.io/LectureComputerScience/'
  use_edit_page_button  : true
  use_issues_button     : true
  use_repository_button : true
  use_multitoc_numbering: false
  extra_footer          : |
    <p>
    <img src='https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg' height='31'/>
    | By Team Fire | Contacts and Infos: <a href='https://cce.uni-wuppertal.de/en.html'>CCE@BUW</a> and <a href='https://www.fz-juelich.de/ias/ias-7/EN/Research/Fire_Dynamics/_node.html'>IAS-7@FZJ</a>
    </br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </p>
  extra_navbar          : ''

###############################################################################
# Interact link settings
# notebook_interface : "notebook"

###############################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright : false
    
###############################################################################
# MyST extensions
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - html_image
    - amsmath

###############################################################################
# Launch button settings
repository:
  url            : "https://github.com/FireDynamics/LectureComputerScience"
  branch         : main
  path_to_book   : "book"

# launch_buttons:
#   jupyterhub_url : https://io.cce.uni-wuppertal.de/firesim_ss2020/

launch_buttons:
  binderhub_url  : ''
  jupyterhub_url : ''


#latex:
#  latex_engine                : "xelatex"
#  latex_documents:
#    targetname: book.tex
